### ISSUE TITLE
Setting the Size of the Node

### ISSUE THREAD

**Issue by agnesnatasya** [vasturiano/icicle-chart#3]
**Describe the bug**
I am building an icicle chart, with 4 to 5 levels (columns), from left to right. The labels on the first 3 columns are much shorter (all <30 characters) than the labels on the 4th and 5th column (can be > 100 characters). I would like to adjust the width of these columns, by setting the first 3 column to have much less width than the 4th and 5th column. 

Setting the width using a function in the `.size()` parameter does not seem to work as I expected. It changes the height of the cell in LR orientation, and not the width. 

**To Reproduce**
1. For ease, create a 3 (no need 5) column icicle chart. You can use my data sample
```
let data =  {
    "name": "root",
    "children": [
        {
            "name": "First Col",
            "children": [
                {
                    "name": "Second Col", 
                    "children": [
                        {"name": "Third Col 1", "value": 1}, 
                        {"name": "Third Col 2", "value": 1}, 
                        {"name": "Third Col 3", "value": 1}
                ]
            }
        ]
    }
]
}
```

2. In the JavaScript script, put size parameter, a function that returns value according to which column it is, for example 
```
Icicle()
    .data(data)
    .size(d =>  {
        if (d.name.substring(0,5) == 'First') {
            return 10
        } else if (d.name.substring(0, 5) == 'Secon') {
            return 10
        } else {
            return 300
        }
    })
    (document.getElementById('myDiv'));
```

**Expected behavior**
The width of the first and second column should be much less than the third column. 

**Screenshots**
However, instead of changing the width, the height change. 
This is the sizes without setting the `.size()` parameter
<img width="1264" alt="tmp_6snYCunvtr" src="https://user-images.githubusercontent.com/44172431/101271019-1161d100-37ba-11eb-9622-cfe8559b089d.png">

This is the sizes after setting the `.size()` parameter
<img width="1264" alt="tmp_Dotl2Lw54k" src="https://user-images.githubusercontent.com/44172431/101271007-eb3c3100-37b9-11eb-90ef-230084a2f4a9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, Chrome

Your help will be very appreciated! :)

**Comment by vasturiano** [comment]
@agnesnatasya thanks for reaching out.

Yes, you are right that the `.size()` only affects the height of the segments. The width is set constant for all the levels. That is by design. 

The main reason behind, once you think about it, is that the area of every rectangle is proportional to the value that it contains. Since this is a hierarchical chart, each level's area should be equal to the area of all its children. If the width of each level was made variable (for labelling purposes) this would introduce a distortion in the data and the proportionality would no longer be true.

Hope that makes sense.

**Comment by agnesnatasya** [comment]
@vasturiano Thank you so much for your reply! I see, that explains a lot for me.

My data in the 4th and 5th column are quite long, it is usually a URL. If the width of the chart is small, the data in the 4th and 5th column is cut. So I need to make the chart width to be very very big in order to fit my 4th and 5th column. 

Do you have any suggestions on how to not make the chart width to be very big?

I also tried to enlarge the height of the cell, and wrap the text. However, I can't find a way to enlarge the cell height and wrap the text.

**Comment by vasturiano** [comment]
@agnesnatasya you can set the chart width and height using the methods `.width(px)` and `.height(px)`.

As for the labels you can apply some styling by overriding the css specified here: 
https://github.com/vasturiano/icicle-chart/blob/24872f2efc3c8ce0b1bec412d613989c3af513ef/src/icicle.css#L15-L21

Unfortunately wrapping is not that simple because these are [SVG text elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text).

Another thing you can do is include the full text on the tooltip instead, using the `tooltipContent` method.

**Comment by agnesnatasya** [comment]
@vasturiano Thank you so much for your suggestion, really appreciate it!
